[2025-04-08T15:02:07.225+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_pipeline_dag.initialize_minio_client manual__2025-04-08T15:02:02.751103+00:00 [queued]>
[2025-04-08T15:02:07.230+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_pipeline_dag.initialize_minio_client manual__2025-04-08T15:02:02.751103+00:00 [queued]>
[2025-04-08T15:02:07.231+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-04-08T15:02:07.241+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): initialize_minio_client> on 2025-04-08 15:02:02.751103+00:00
[2025-04-08T15:02:07.247+0000] {standard_task_runner.py:57} INFO - Started process 413 to run task
[2025-04-08T15:02:07.249+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'minio_pipeline_dag', 'initialize_minio_client', 'manual__2025-04-08T15:02:02.751103+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/app.py', '--cfg-path', '/tmp/tmpe5ckgwsc']
[2025-04-08T15:02:07.251+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask initialize_minio_client
[2025-04-08T15:02:07.290+0000] {task_command.py:415} INFO - Running <TaskInstance: minio_pipeline_dag.initialize_minio_client manual__2025-04-08T15:02:02.751103+00:00 [running]> on host 402609eca8dd
[2025-04-08T15:02:07.346+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_team' AIRFLOW_CTX_DAG_ID='minio_pipeline_dag' AIRFLOW_CTX_TASK_ID='initialize_minio_client' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T15:02:02.751103+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-08T15:02:02.751103+00:00'
[2025-04-08T15:02:07.359+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-04-08T15:02:07.362+0000] {python.py:194} INFO - Done. Returned value was: <minio.api.Minio object at 0x78fa727e0280>
[2025-04-08T15:02:07.367+0000] {xcom.py:661} ERROR - Object of type Minio is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2025-04-08T15:02:07.368+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 178, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'minio.api.Minio'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2477, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 244, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 659, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Minio is not JSON serializable
[2025-04-08T15:02:07.378+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=minio_pipeline_dag, task_id=initialize_minio_client, execution_date=20250408T150202, start_date=20250408T150207, end_date=20250408T150207
[2025-04-08T15:02:07.388+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 8 for task initialize_minio_client (Object of type Minio is not JSON serializable; 413)
[2025-04-08T15:02:07.421+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-04-08T15:02:07.437+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
